# Generated by Django 5.0.3 on 2026-02-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstat',
            name='time_taken',
            field=models.FloatField(default=0.0, help_text='Time taken to answer in seconds'),
        ),
    ]
