# Generated by Django 5.0.1 on 2026-02-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_quizstat_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstat',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.challenge'),
        ),
    ]
