# Generated by Django 5.0.1 on 2026-02-10 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0006_quizstat_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('drag_drop', 'Drag & Drop Game'), ('beer_cup', 'Beer Cup Game'), ('jigsaw', 'Jigsaw Puzzle Game')], max_length=20)),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('correct_answers', models.PositiveSmallIntegerField()),
                ('total_time_seconds', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('drag_drop', 'Drag & Drop Game'), ('beer_cup', 'Beer Cup Game'), ('jigsaw', 'Jigsaw Puzzle Game')], max_length=20)),
                ('question_id', models.IntegerField(help_text='Question ID from the game')),
                ('question_text', models.TextField(blank=True, help_text='The question text for reference')),
                ('selected_answer', models.TextField(help_text='The answer selected by the player')),
                ('correct_answer', models.TextField(blank=True, help_text='The correct answer for reference')),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.FloatField(default=0.0, help_text='Time taken to answer in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['player', 'game_type'], name='gameplay_ga_player__d1d8b2_idx'), models.Index(fields=['game_type', 'created_at'], name='gameplay_ga_game_ty_814580_idx')],
            },
        ),
    ]
