# Generated by Django 5.0.1 on 2026-02-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0008_userfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='additional_comments',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='favorite_game',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='games_experience',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='would_recommend',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='what_can_be_better',
            field=models.TextField(blank=True, help_text='Suggestions for improvement'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='what_is_confusing',
            field=models.TextField(blank=True, help_text='What was confusing or unclear'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='what_works',
            field=models.TextField(blank=True, help_text='What worked well for the user'),
        ),
    ]
