# Generated by Django 5.0.1 on 2026-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0009_remove_userfeedback_additional_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='cluster_sales_area',
            field=models.CharField(blank=True, default='', help_text="Player's cluster or sales area", max_length=200),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text="Player's full name", max_length=200),
        ),
    ]
