# Generated by Django 5.0.1 on 2026-02-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0010_userfeedback_cluster_sales_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='digital_sales_tool',
            field=models.CharField(blank=True, default='', help_text='Selected digital sales tool', max_length=100),
        ),
    ]
