# Generated by Django 5.0.3 on 2026-02-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0012_alter_userfeedback_digital_sales_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='answers_data',
            field=models.JSONField(blank=True, help_text='Structured JSON of all answers/results', null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_correct',
            field=models.BooleanField(blank=True, help_text='Overall result (e.g. jigsaw solved correctly)', null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='set_a_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Set A correct answers (drag_drop)', null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='set_a_total',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Set A total questions (drag_drop)', null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='set_b_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Set B correct answers (drag_drop)', null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='set_b_total',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Set B total questions (drag_drop)', null=True),
        ),
    ]
